# Nombre de tu aplicación
spring.application.name=ElAlephSystem

# Configuración del puerto dinámica para servidores en la nube
server.port=${PORT:8080}

# Conexión a Base de Datos (Usa la nube si existe, sino usa tu localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/el_aleph_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:g1234567P}

# Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Thymeleaf (Frontend)
spring.thymeleaf.cache=false

# Permitir subida de archivos grandes (comprobantes de fotos pesadas)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB